root = "."
tmp_dir = ".air"

[build]
  cmd = "go build -o .air/main ."
  bin = ".air/main"
  delay = 500
  exclude_dir = [".air", ".data", "app", "static", "deployment", "docs"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go"]
  kill_delay = "2s"
  rerun_delay = 500
  send_interrupt = true

[log]
  time = true

[color]
  app = "green"
  build = "yellow"
  main = "magenta"
  runner = "cyan"
  watcher = "cyan"

[misc]
  clean_on_exit = true
