package handlers

import (
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/labstack/echo/v4"
	"github.com/nathanamorin/local-podcasts/podcast"
	"gorm.io/gorm"
	"k8s.io/klog/v2"
)

const UserDataPath = "user_data"

type podcastList struct {
	Podcasts []podcast.Podcast `json:"podcasts"`
}

// Handler holds shared dependencies for all route handlers.
type Handler struct {
	config podcast.Config
	pw     *podcast.PodcastWatcher
	db     *gorm.DB
}

func New(config podcast.Config, pw *podcast.PodcastWatcher, db *gorm.DB) *Handler {
	return &Handler{config: config, pw: pw, db: db}
}

// Register attaches all routes to the given Echo instance.
func (h *Handler) Register(e *echo.Echo) {
	e.GET("/refresh", h.Refresh)

	e.GET("/podcasts", h.ListPodcasts)
	e.POST("/podcasts", h.AddPodcast)
	e.GET("/podcasts/:podcast_id", h.GetPodcast)
	e.GET("/podcasts/:podcast_id/image", h.GetPodcastImage)
	e.GET("/podcasts/:podcast_id/episodes/:episode_id/stream", h.StreamEpisode)

	e.GET("/rss/all", h.RSSAll)

	// These status endpoints are not intended to provide secure user data management.
	// The only data stored are podcast status, played, etc. In the intended local
	// network environment, a simple shared token generated by the client is used.
	// If lost, this token can't be recovered from the server side.
	e.GET("/client-status/:key-id", h.GetClientStatus)
	e.PUT("/client-status/:key-id", h.PutClientStatus)
	e.DELETE("/client-status/:key-id", h.DeleteClientStatus)
}

func (h *Handler) EnqueueAll() {
	if !h.pw.QueueEmpty() {
		klog.Infof("podcasts still in update queue, skipping cron update")
		return
	}
	podcasts, err := h.pw.ListPodcasts()
	if err != nil {
		klog.Errorf("error listing podcasts on refresh: %s", err)
		return
	}
	for _, p := range podcasts {
		h.pw.EnqueuePodcast(p)
	}
}

func (h *Handler) Refresh(c echo.Context) error {
	h.EnqueueAll()
	return c.JSON(http.StatusOK, map[string]string{"status": "ok"})
}

func (h *Handler) ListPodcasts(c echo.Context) error {
	podcasts, err := h.pw.ListPodcasts()
	if err != nil {
		klog.Errorf("error listing podcasts: %s", err)
		return c.String(http.StatusInternalServerError, `{"error": "error listing podcasts"}`)
	}

	for idx := range podcasts {
		podcasts[idx].Episodes = nil
	}

	return c.JSON(http.StatusOK, podcastList{Podcasts: podcasts})
}

func (h *Handler) AddPodcast(c echo.Context) error {
	jsonData := make(map[string]interface{})
	if err := json.NewDecoder(c.Request().Body).Decode(&jsonData); err != nil {
		klog.Errorf("error reading json request: %s", err)
		return c.String(http.StatusBadRequest, `{"error": "invalid request"}`)
	}

	rssUrl, ok := jsonData["rss_url"]
	if !ok {
		return c.String(http.StatusBadRequest, `{"error": "rss_url must be provided in json request body"}`)
	}

	podcastData, err := podcast.AddPodcast(h.config, h.db, rssUrl.(string))
	if err != nil {
		klog.Errorf("error processing podcast rss url %s: %s", rssUrl.(string), err)
		return c.String(http.StatusBadRequest, `{"error": "error processing podcast rss url"}`)
	}

	h.pw.InvalidateCache()
	h.pw.EnqueuePodcast(*podcastData)

	return c.JSON(http.StatusOK, podcastData)
}

func (h *Handler) GetPodcast(c echo.Context) error {
	podcastData, err := h.pw.GetPodcast(c.Param("podcast_id"))
	if err != nil {
		klog.Errorf("error getting podcast: %s", err)
		return c.String(http.StatusInternalServerError, `{"error": "error getting podcast"}`)
	}

	return c.JSON(http.StatusOK, podcastData)
}

func (h *Handler) GetPodcastImage(c echo.Context) error {
	podcastData, err := h.pw.GetPodcast(c.Param("podcast_id"))
	if err != nil {
		klog.Errorf("error getting podcast: %s", err)
		return c.String(http.StatusInternalServerError, `{"error": "error getting podcast"}`)
	}

	imagePath := podcastData.GetImage(h.config)

	c.Response().Status = http.StatusOK
	c.Response().Header().Set("Cache-Control", "max-age=604800")
	http.ServeFile(c.Response().Writer, c.Request(), imagePath)
	return nil
}

func (h *Handler) StreamEpisode(c echo.Context) error {
	podcastData, err := h.pw.GetPodcast(c.Param("podcast_id"))
	if err != nil {
		klog.Errorf("error getting podcast: %s", err)
		return c.String(http.StatusInternalServerError, `{"error": "error getting podcast"}`)
	}

	filePath, err := podcastData.GetAudioFile(h.config, c.Param("episode_id"))
	if err != nil {
		klog.Errorf("error getting stream: %s", err)
		return c.String(http.StatusInternalServerError, `{"error": "error getting stream"}`)
	}

	c.Response().Status = http.StatusOK
	http.ServeFile(c.Response().Writer, c.Request(), filePath)
	return nil
}

func (h *Handler) RSSAll(c echo.Context) error {
	podcasts, err := h.pw.ListPodcasts()
	if err != nil {
		klog.Errorf("error getting podcasts for rss: %s", err)
		return c.String(http.StatusInternalServerError, `{"error": "error getting podcast"}`)
	}

	host := c.Request().Header.Get("X-Forwarded-Host")
	scheme := c.Request().Header.Get("X-Forwarded-Proto")

	if host == "" {
		host = c.Request().Host
	}
	if scheme == "" {
		scheme = c.Request().URL.Scheme
	}
	if scheme == "" {
		scheme = "http"
	}

	rss, err := podcast.RenderPodcasts(podcasts, scheme+"://"+host)
	if err != nil {
		klog.Errorf("error rendering rss feed: %s", err)
		return c.String(http.StatusInternalServerError, `{"error": "error getting rss feed"}`)
	}

	return c.Blob(http.StatusOK, "application/rss+xml", []byte(rss))
}

func (h *Handler) clientInfo(c echo.Context) (key string, filePath string) {
	token := strings.Replace(c.Request().Header.Get("Authorization"), "Basic ", "", 1)
	key = c.Param("key-id")
	hashedToken := fmt.Sprintf("%x", sha256.Sum256([]byte(token+key)))
	filePath = filepath.Join(h.config.FileHome, UserDataPath, hashedToken)
	return
}

func (h *Handler) GetClientStatus(c echo.Context) error {
	key, filePath := h.clientInfo(c)

	if _, err := os.Stat(filePath); errors.Is(err, os.ErrNotExist) {
		return c.JSONBlob(http.StatusNotFound, []byte(`{"error": "key not found"}`))
	} else if err != nil {
		klog.Errorf("error fetching client status key %s: %s", key, err)
		return c.JSONBlob(http.StatusInternalServerError, []byte(`{"error": "internal server error"}`))
	}

	f, err := os.Open(filePath)
	if err != nil {
		klog.Errorf("error opening client status key %s: %s", key, err)
		return c.JSONBlob(http.StatusInternalServerError, []byte(`{"error": "internal server error"}`))
	}
	defer f.Close()

	byteValue, err := ioutil.ReadAll(f)
	if err != nil {
		klog.Errorf("error reading client status key %s: %s", key, err)
		return c.JSONBlob(http.StatusInternalServerError, []byte(`{"error": "internal server error"}`))
	}

	c.Response().Header().Add(echo.HeaderContentType, "text/plain")
	c.Response().Header().Add("Cache-Control", "no-cache")
	_, err = c.Response().Write(byteValue)
	return err
}

func (h *Handler) PutClientStatus(c echo.Context) error {
	key, filePath := h.clientInfo(c)

	data, err := ioutil.ReadAll(c.Request().Body)
	if err != nil {
		klog.Errorf("error reading data while updating client status key %s: %s", key, err)
		return c.JSONBlob(http.StatusInternalServerError, []byte(`{"error": "internal server error"}`))
	}

	if err = ioutil.WriteFile(filePath, data, 0764); err != nil {
		klog.Errorf("error writing data while updating client status key: %s", key)
		return c.JSONBlob(http.StatusInternalServerError, []byte(`{"error": "internal server error"}`))
	}

	return c.JSONBlob(http.StatusOK, []byte(`{"status": "success"}`))
}

func (h *Handler) DeleteClientStatus(c echo.Context) error {
	key, filePath := h.clientInfo(c)

	if err := os.Remove(filePath); err != nil {
		klog.Errorf("error removing client status key %s: %s", key, err)
		return c.JSONBlob(http.StatusInternalServerError, []byte(`{"error": "internal server error"}`))
	}

	return c.JSONBlob(http.StatusOK, []byte(`{"status": "success"}`))
}
